# Copyright (C) 2019 The Trustees of Indiana University
# SPDX-License-Identifier: BSD-3-Clause

title: Rivet Jekyll Theme

kramdown:
  parse_block_html: true
sass:
  sass_dir: _sass
  style: compressed # what are the other options?